easy_admin:
    entities:
        # List the entity class name you want to manage
        - App\Entity\User
#        - App\Entity\Product
#        - App\Entity\Category
        - App\Entity\UserGroup
        - App\Entity\Map2u\Core\SidebarMenu
